config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
    resources :blogs do
      collection do
        post :confirm
      end
    end
   resources :sessions, only: [:new, :create, :destroy]
   resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :title, presence: true, uniqueness: true, length:{ maximum:100}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
                    #format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
  if params[:back]
    render :new
  else
    if @blog.save
      redirect_to blogs_path
    else
      render 'new'
    end
   end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "Blog mis à jour avec succès"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
      redirect_to blogs_path, notice: "Blog supprimé avec succès."
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
      render :new if @blog.invalid?
  end

  private

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:content, :image, :image_cache)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     redirect_to blogs_path
   else
     flash.now[:danger] = "Je n'ai pas réussi à me connecter"
     render 'new'
   end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Déconnecté'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
   if @user.save
     redirect_to user_path(@user.id)
   else
     render 'new'
   end
  end

   def show
     @user = User.find(params[:id])
   end

   private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
   if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
     confirm_blogs_path
   elsif action_name == 'edit'
     blog_path
   end  
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2>Entrer Quelque chose </h2>
    </div>
  <% end %>
<div class="blog_content">
  <%= form.label :content %>
  <%= form.text_field :content %>
  </div>
  <div class="field">
  <%= form.label :image %>
  <%= form.file_field :image %>
  </div>
  <%= form.submit 'Submit' %>
<% end %>
<br>
<%= link_to "Retour", blogs_path %>

app/views/blogs/confirm.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Chercher</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>Amis </span>
          <span class="blue-line"> | </span>
          <span>Parametres</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "S'enregistrer", new_user_path %>
            <%= link_to "Connexion", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
<div class="general-box">
  <h3>Confirmer ?</h3>
  <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p><%= @blog.content %></p>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.hidden_field :image_cache %>
    <br>
    <br>
    <p><%= form.submit "Publier" %><p/>
  <% end %>
  <%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <p><%= form.submit "Non", name: "retour" %><p/>
  <% end %>
</div>
</main>

app/views/blogs/edit.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Chercher</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <a href="#"<span>Creer</span></a>
          <span class="blue-line"> | </span>
          <a href="#"<span>Parametres</span></a>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "S'inscrire", new_user_path %>
            <%= link_to "Se connecter", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h1>Modification du Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', blogs_path %>
  </div>
</main>

app/views/blogs/index.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Recherche</div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <a href= "#"<span>Amis</span></a>
          <span class="blue-line"> | </span>
          <a href="#"<span>Parametre</span></a>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "S'inscrire", new_user_path %>
            <%= link_to "Se connecter", new_session_path %>

          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="main-block">
    <div class="main-block-left">
      <%= image_tag "acount-pic.png", size: '20x20', class: 'left-acount-pic' %>
      <br>
      <div class="left-box-focus">
        <%= image_tag "actualites.png", size: '20x20' %>
        <a href="#"<span>Amis</span></a>
        <%= image_tag "reader.png", size: '20x20', class: 'left-reader' %>
      </div>
      <div class="left-box-unfocus">
        <%= image_tag "messenger.jpg", size: '20x20' %>
        <a href ="#" target="_blank"<span>Messenger</span></a>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "market.png", size: '20x20' %>
        <a href ="https://www.facebook.com/watch" target="_blank"<span>Marketplace</span></a>
      </div>
      <div class="discover">Vos raccourcis</div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "group.png", size: '20x20' %>
        <a href="https://www.facebook.com/search/top?q=group%20facebook" target="_blank"<span>Group</span></a>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "flag.png", size: '20x20' %>
        <a href="https://www.facebook.com/search/top?q=page%20facebook" target="_blank"<span>page</span></a>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "evenement.png", size: '20x20' %>
        <a href="https://www.facebook.com/events/?acontext=%7B%22action_history%22%3A%22null%22%7D" target="_blank"<span>Evenement</span></a>
      </div>
      <div class="left-box-unfocus-alt">
        <%= image_tag "amis.png", size: '20x20' %>
        <a href="https://www.facebook.com/friends" target="_blank"<span>Liste d'amis</span></a>
      </div>
      <div class="left-box-more">
        <%= image_tag "plus.png", size: '20x20' %>
        <a href="#"<span>Voir plus...</span></a>
      </div>
    </div>
    <div class="main-block-center">
      <div class="main-box-new">
        &nbsp;&nbsp;
        <button type="button">
          <%= link_to 'Creer Un Poste', new_blog_path %>
        </button>
      </div>
      <% @blogs.each do |blog| %>
      <div class="main-box">
        <table>
          <tr>
            <td><%= image_tag "acount-pic.png", size: '40x40', class: 'box-acount-pic' %></td>
            <td>
            <div class="box-name"><%= blog.user.name %></div>
            <div class="box-time"><%= blog.created_at.try(:strftime," %m mois %d jour ") %></div>
            </td>
            <td class="detail"><%= link_to 'Détail', blog_path(blog.id) %></td>
            <td><%= link_to "Edite", edit_blog_path(blog.id) %></td>
            <td>
              <%= link_to 'Supprimer', blog_path(blog.id), method: :delete, data: { confirm: 'Confirmer？' } %>
            </td>
          </tr>
        </table>
        <div class="box-content">
        <%= blog.content %>
        </div>
        <% if blog.image.file.nil? %>
          <% else %>
        <div class="box-pic">
          <%= image_tag blog.image.url %>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
    <div class="main-block-right">
      <span>BENIN</span>
      <div class="recommend-group">
        <%= image_tag "logBenjust.jpg", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">Benin Justice</p>
              <p class="grey-line">Juste</p>
            </td>
            <td>
              <a href="#" target="_blank"<div class="entry_btn">Visite !</div></a>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "japan.png", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">Le Japon</p>
              <p class="grey-line">Fraiche</p>
            </td>
            <td>
            <a href="#" target="_blank"<div class="entry_btn">Visite !</div></a>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "benlogo.png", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">Le Drapeau</p>
              <p class="grey-line">L'unique</p>
            </td>
            <td>
            <a href="#" target="_blank"<div class="entry_btn">Visite !</div></a>
            </td>
          </tr>
        </table>
      </div>
      <div class="recommend-group">
        <%= image_tag "benlogo.png", class: 'recommend-pic' %>
        <table>
          <tr>
            <td>
              <p class="blue-line">Le Drapeau</p>
              <p class="grey-line">L'unique</p>
            </td>
            <td>
            <a href="#" target="_blank"<div class="entry_btn">Visite !</div></a>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/blogs/new.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Chercher</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>Parametres</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "s'inscrire", new_user_path %>
            <%= link_to "connexion", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h1>Nouvelle publication</h1>

    <%= render 'form' %>

    <%= link_to 'Retour', blogs_path %>
  </div>
</main>

app/views/blogs/show.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Recherche</div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <a href="https://www.facebook.com/messages"<span>Messenger</span></a>
          <span class="blue-line"> | </span>
          <a href="#"<span>Paramètre</span></a>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "S'inscrire", new_user_path %>
            <%= link_to "Connexion", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="detail-box">

    <h1>Detail</h1>

    <p><%= @blog.content %></p>
    <p>
      <% if @blog.image.file.nil? %>
      <% else %>
        <%= image_tag @blog.image.url %>
      <% end %>
    </p>

    <%= link_to 'Modifier', edit_blog_path(@blog) %> |
    <%= link_to 'Retour', blogs_path %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Chercher</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td> </td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <span>Trouver des amis</span>
          <span class="blue-line"> | </span>
          <span>Parametres</span>
          <span class="blue-line"> | </span>
          <span>うに</span>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Inscription", new_user_path %>
            <%= link_to "Se connecter", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="general-box">
    <h1>INSCRIVEZ-VOUS ICI !!!</h1>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2> Vous avez fais <%= pluralize(@user.errors.count, "erreurs") %> </h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name, 'Nom Du Compte:' %>
      <p class="hey"><%= f.text_field :name %><br></p>
      <%= f.label :email, 'E-mail Adress:' %>
      <p class="hey"><%= f.email_field :email %><br></p>
      <%= f.label :password, 'Mot de passe :' %>
      <p class="hey"><%= f.password_field :password %><br></p>
      <%= f.label :password_confirmation, 'Mot de passe (confirmation) :' %>
      <p class="hey"><%= f.password_field :password_confirmation %></p>
      <br>
      <br>
      <p><%= f.submit "Créer un compte" %></p>
    <% end %>
  </div>
</main>

app/views/users/show.html.erb
<header>
  <table>
    <tr>
      <td><%= image_tag "facebook.png", class: 'fakebook-logo' %></td>
      <td>
        <div class="fake-search-box">
          <div class="search-sujest">Chercher</div>
          <div class="search-content"></div>
          <div class="search-img"><%= image_tag "Search.png", class: 'search-png' %></div>
        </div>
      </td>
      <td><%= image_tag "acount-pic.png", size: '25x25', class: 'header-acount-pic' %></td>
      <td>
        <div class="header-menu">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
          <span>
          <% if logged_in? %>
            <%= link_to "#{current_user.name}", user_path(current_user.id) %>
          </span>
          <span class="blue-line"> | </span>
          <span>
            <%= link_to "Accueil", blogs_path %>
          </span>
          <span class="blue-line"> | </span>
          <a href="#"<span>Trouver des amis</span></a>
          <span class="blue-line"> | </span>
          <a href="#"<span>Parametres</span></a>
          <span class="blue-line"> | </span>
          <span>
          <%= link_to "Deconnexion", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Inscription", new_user_path %>
            <%= link_to "Connexion", new_session_path %>
          <% end %>
          </span>
        </div>
      </td>
    </tr>
  </table>
</header>

<main>
  <div class="profile">
    <h1>Profile de <%= @user.name %></h1>
    <span><%= image_tag "acount-pic.png", size: '300x300', class: 'profile-acount-pic' %></span>
    <p>Adresse électronique : <%= @user.email %></p>
  </div>
</main>